# Generated by Django 3.1.3 on 2021-02-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210209_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='suhu',
            name='d_hum',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
